### ISSUE TITLE
Refreshing userToken

### ISSUE THREAD

**Issue by bryanmcgrane** [pajlada/go-twitch-pubsub#40]
I'm really thankful for this library! I have a question regarding what to do when I inevitably have to refresh my userToken.

Since userTokens have a 4 hour lifespan, I have a background process that refreshes mine on a fixed interval. When I refresh this token, should I also re-create my Topics or is that unnecessary?

How do others handle this?

Here's the userToken I'm referencing.
```
	// OAuth token for userID with chat_login (or chat:read?) scope
        // Rotates every 4 hours
	userToken := "abcdefg"

	// Listen to a topic
	pubsubClient.Listen(twitchpubsub.ModerationActionTopic(userID, channelID), userToken)

	// Specify what callback is called when that topic receives a message
	pubsubClient.OnModerationAction(func(channelID string, event *twitchpubsub.ModerationAction) {
		fmt.Println(event.CreatedBy, event.ModerationAction, "on", event.TargetUserID)
	})
```

Thanks for the help!

**Comment by pajlada** [comment]
Depends a bit on how long your application lives - topics are stored in the client with the token for reconnection so if you lose the pubsub connection, they'd fail to reconnect since the token has been disconnected.
The safe choice is to just recreate the client & listens entirely when you refresh your token. You just need to be careful to not run into any rate limits during the reconnect since we don't handle that super well

**Comment by bryanmcgrane** [comment]
Great thank you for the advice. I think I've got that all working now. Much appreciated!
